export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAILED = 'LOGINFAILED';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERFAILED = 'REGISTERFAILED';
export const LOGOUT = 'LOGOUT';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES = 'CATEGORIES';

export const GETMENU = 'GETMENU';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_EXTRAS = 'GET_EXTRAS';
export const ADD_EXTRAS = 'ADD_EXTRAS';

export const NEWADDRESS = 'NEWADDRESS';
export const GETADDRESS = 'GETADDRESS';
export const DELETEADDRESS = 'DELETEADDRESS';

export const GETBRANCHES = 'GETBRANCHES';

export const ADD_SERVICE_TYPE = "ADD_SERVICE_TYPE"

export const GETOFFERS = 'GETOFFERS';
export const GETOFFERSMENU = 'GETOFFERSMENU';

export const ADDTOCART = 'ADDTOCART';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const INCREMENTCART = 'INCREMENTCART';
export const DECREMENTCART = 'DECREMENTCART';

export const APPLY_LANGUAGE = "APPLY_LANGUAGE"